name: InfernalExpansion
author: Kiirzu
description: A Slimefun4 addon that adds a variety of runes and nether-related mechanics.
main: ga.kirzu.infernalexpansion.InfernalExpansion
website: https://github.com/NotKirzu/InfernalExpansion
version: ${project.version}
api-version: 1.16
depend:
  - Slimefun